### ISSUE TITLE
Types are missing

### ISSUE THREAD

**Issue by kalypzo** [SaiHemanthBR/vault-api#11]
Types are not being properly exported in the published project. If you look at the `vault-api/dist/index.d.ts` file in the `node_modules` folder, you'll notice it attempts to reference the types from the `./types` folder. This folder doesn't exist in the package so types are basically missing in typescript. I believe the issue may be with the `.npmignore` file ignoring the `types` folder, so it doesn't make it to the distributed package.

**Comment by SaiHemanthBR** [comment]
Hey thanks for letting me know. I’ll look into it.

**Comment by SaiHemanthBR** [comment]
Updated `.npmignore` to allowlist types dir. This issue should be fixed in `1.1.1`. If you have any issue, please feel free to reopen the issue.
